/**
 * code-agent.js — يبني هيكل المشروع البرمجي الكامل
 *
 * القواعد المطبقة:
 *  - rule-058: اسم preset = 'Web' دائماً
 *  - rule-070: platform = 'Web' في Godot 4.x
 *  - rule-071: variant/thread_support=false
 *  - rule-087: askGemini(prompt, temperature, options, caller)
 *  - rule-089: كل الردود JSON
 *  - rule-098: askGemini من _gemini.js فقط
 *  - rule-099: [INFO]/[OK]/[ERROR] بدون إيموجي
 */
import { writeFileSync, mkdirSync, existsSync, readFileSync, readdirSync } from 'fs';
import { join, dirname }  from 'path';
import { fileURLToPath }  from 'url';
import { askGemini }      from './_gemini.js';
import { soulContext }    from './_soul.js';
import { readForAgent }   from './library-builder-agent.js';
import { logger }         from '../logger.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

// ── كتابة ملف مع إنشاء المجلد ────────────
function writeProjectFile(slug, filename, content) {
  const dir = join(__dirname, '..', 'godot-projects', slug);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, filename), content, 'utf8');
  logger.info(`[OK] Written: ${slug}/${filename}`);
}

// ── export_presets.cfg ثابت ───────────────
function generateExportPresets() {
  return `[preset.0]
name="Web"
platform="Web"
runnable=true
dedicated_server=false
custom_features=""
export_filter="all_resources"
include_filter=""
exclude_filter=""
export_path="./index.html"
patches=PackedStringArray()
encryption_include_filters=""
encryption_exclude_filters=""
encrypt_pck=false
encrypt_directory=false

[preset.0.options]
custom_template/debug=""
custom_template/release=""
variant/extensions_support=false
variant/thread_support=false
vram_texture_compression/for_desktop=true
vram_texture_compression/for_mobile=false
html/export_icon=true
html/custom_html_shell=""
html/head_include=""
html/canvas_resize_policy=2
html/focus_canvas_on_start=true
html/experimental_virtual_keyboard=false
progressive_web_app/enabled=false
progressive_web_app/offline_page=""
progressive_web_app/display=1
progressive_web_app/orientation=0
progressive_web_app/icon_144x144=""
progressive_web_app/icon_180x180=""
progressive_web_app/icon_512x512=""
progressive_web_app/background_color=Color(0, 0, 0, 1)
`;
}

// ── project.godot ثابت — لا يحتاج Gemini ─
function buildProjectGodot(idea) {
  return `; Engine configuration file.
; Generated by universe agents — Godot 4.6.2
config_version=5

[application]
config/name="${idea.name?.en || idea.id}"
run/main_scene="res://main_scene.tscn"
config/features=PackedStringArray("4.6", "Forward Plus")
config/icon="res://icon.svg"

[display]
window/size/viewport_width=1280
window/size/viewport_height=720

[input]
move_forward={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":87,"physical_keycode":87,"key_label":87,"unicode":119,"echo":false)]
}
move_back={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":83,"physical_keycode":83,"key_label":83,"unicode":115,"echo":false)]
}
move_left={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":65,"physical_keycode":65,"key_label":65,"unicode":97,"echo":false)]
}
move_right={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":68,"physical_keycode":68,"key_label":68,"unicode":100,"echo":false)]
}
jump={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":32,"physical_keycode":32,"key_label":32,"unicode":32,"echo":false)]
}
fire={
"deadzone": 0.5,
"events": [Object(InputEventMouseButton,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"button_mask":1,"position":Vector2(0, 0),"global_position":Vector2(0, 0),"factor":1.0,"button_index":1,"canceled":false,"pressed":true,"double_click":false)]
}
ui_cancel={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":4194305,"physical_keycode":4194305,"key_label":4194305,"unicode":0,"echo":false)]
}

[rendering]
renderer/rendering_method="forward_plus"
`;
}

// ── قواعد GDScript الآلية ─────────────────
function applyScriptRules(filename, code) {
  if (typeof code !== 'string') return code;
  code = code.replace(/^    /gm, '\t').replace(/^  /gm, '\t');
  if (code.includes('await') && code.includes('queue_free()') && !code.includes('is_inside_tree')) {
    code = code.replace(/(\tqueue_free\(\))/g, '\tif is_inside_tree():\n\t\tqueue_free()');
  }
  if (filename === 'player.gd' && !code.includes('add_to_group("player")')) {
    code = code.replace('func _ready():\n', 'func _ready():\n\tadd_to_group("player")\n');
  }
  if (filename === 'enemy.gd' && !code.includes('add_to_group("enemy")')) {
    code = code.replace('func _ready():\n', 'func _ready():\n\tadd_to_group("enemy")\n');
  }
  return code;
}

// ── إصلاح load_steps ─────────────────────
function fixLoadSteps(content) {
  if (typeof content !== 'string') return content;
  const ext = (content.match(/^\[ext_resource /gm) || []).length;
  const sub = (content.match(/^\[sub_resource /gm) || []).length;
  return content.replace(/\[gd_scene load_steps=\d+/, `[gd_scene load_steps=${ext + sub}`);
}

// ── تحميل وصفات المخترع ──────────────────
function loadRecipes(domain) {
  const recipesDir = join(__dirname, '..', 'godot-recipes', domain);
  if (!existsSync(recipesDir)) return '';
  try {
    const files = readdirSync(recipesDir).filter(f => f.endsWith('.meta.json'));
    if (!files.length) return '';
    return files.slice(0, 3).map(f => {
      const meta = JSON.parse(readFileSync(join(recipesDir, f), 'utf8'));
      return `- ${meta.label}: ${meta.usage}`;
    }).join('\n');
  } catch { return ''; }
}

// ── إضافة اللعبة لـ products.json ────────
function addToProducts(idea, art, worlds) {
  const path     = join(__dirname, '..', 'products.json');
  const products = existsSync(path) ? JSON.parse(readFileSync(path, 'utf8')) : [];
  if (products.find(p => p.id === idea.id)) {
    logger.info('[INFO] Product already exists', { id: idea.id });
    return;
  }
  products.unshift({
    id:           idea.id,
    slug:         idea.id,
    type:         'godot',
    category:     'game',
    status:       'available',
    templateFile: 'godot-wrapper.html',
    godotSlug:    idea.id,
    accent:       art?.accent    || '#00ff88',
    accentRgb:    art?.accentRgb || '0,255,136',
    gradient:     art?.gradient  || '135deg,#020209,#080820',
    name:         idea.name,
    desc:         idea.desc,
    tags:         idea.tags || [],
    iap:          [],
    levels:       worlds?.worlds?.map(w => ({
      id:         w.id,
      name:       w.name,
      difficulty: w.difficulty,
    })) || [],
    controls: {
      ar: { move: 'WASD للتحرك', look: 'الفأرة للنظر', fire: 'كليك يسار', jump: 'مسافة' },
      en: { move: 'WASD to move', look: 'Mouse to look', fire: 'Left click',  jump: 'Space'  },
    },
    generated:   true,
    generatedAt: new Date().toISOString(),
  });
  writeFileSync(path, JSON.stringify(products, null, 2), 'utf8');
  logger.info('[OK] Product added to products.json', { id: idea.id });
}

// ════════════════════════════════════════════
// الدالة الرئيسية
// ════════════════════════════════════════════
export async function run(idea, story, levels, art, template) {
  logger.info('[INFO] Code Agent started', { id: idea.id, type: idea.type });

  const isGodot = idea.type === 'godot';
  if (!isGodot) {
    logger.info('[INFO] Non-Godot project — skipping');
    return { slug: idea.id, files: [], engine: 'phaser' };
  }

  const soul    = soulContext('codeAgent');
  const library = readForAgent('code-agent', 10);
  const slug    = idea.id;
  const files   = [];

  // 1. export_presets.cfg
  writeProjectFile(slug, 'export_presets.cfg', generateExportPresets());
  files.push('export_presets.cfg');

  // 2. project.godot
  writeProjectFile(slug, 'project.godot', buildProjectGodot(idea));
  files.push('project.godot');

  // 3. ملفات GDScript
  logger.info('[INFO] Generating GDScript files...');
  const heroName    = story?.mainCharacter?.name || 'Hero';
  const worldNames  = levels?.worlds?.slice(0, 3).map(w => w.name?.en).join(', ') || '';
  const movementTip = loadRecipes('movement');

  const SCRIPTS = [
    {
      file: 'main_scene.gd',
      prompt: `Godot 4.6.2 GDScript for main_scene.gd.
Game: "${idea.name?.en}". Use Node3D root.
Rules: process_mode = ALWAYS, handle InputEventMouseButton + InputEventScreenTouch to start game, pause/unpause logic.
Return JSON: { "main_scene.gd": "<complete code>" }`
    },
    {
      file: 'player.gd',
      prompt: `Godot 4.6.2 GDScript for player.gd.
Game: "${idea.name?.en}". Hero: ${heroName}.
${movementTip ? `Movement recipe:\n${movementTip}` : ''}
Rules: extends CharacterBody3D, add_to_group("player") in _ready(), WASD movement, mouse look, jump, fire action.
Return JSON: { "player.gd": "<complete code>" }`
    },
    {
      file: 'enemy.gd',
      prompt: `Godot 4.6.2 GDScript for enemy.gd.
Game: "${idea.name?.en}". Worlds: ${worldNames}.
Rules: extends CharacterBody3D, add_to_group("enemy") in _ready(), NavigationAgent3D for pathfinding, attack when close.
Return JSON: { "enemy.gd": "<complete code>" }`
    },
    {
      file: 'weapon.gd',
      prompt: `Godot 4.6.2 GDScript for weapon.gd.
Game: "${idea.name?.en}".
Rules: extends Node3D, preload bullet scene, shoot on fire action, muzzle_point as Marker3D child, fire rate cooldown.
Return JSON: { "weapon.gd": "<complete code>" }`
    },
    {
      file: 'bullet.gd',
      prompt: `Godot 4.6.2 GDScript for bullet.gd.
Rules: extends RigidBody3D, gravity_scale=0.0, linear_velocity on _ready(), _on_body_entered signal handler, is_inside_tree() before queue_free() after await, deal damage to enemy group.
Return JSON: { "bullet.gd": "<complete code>" }`
    },
  ];

  for (const { file, prompt } of SCRIPTS) {
    try {
      const result = await askGemini(
        `${soul}\n${library}\n\n${prompt}`,
        0.7, { topP: 0.9, maxOutputTokens: 4096 }, 'code-agent'
      );
      const code = result[file];
      if (!code || typeof code !== 'string') {
        logger.warn(`[WARN] Missing code for ${file}`);
        continue;
      }
      writeProjectFile(slug, file, applyScriptRules(file, code));
      files.push(file);
    } catch (err) {
      logger.error(`[ERROR] Failed to generate ${file}`, { error: err.message });
    }
  }

  // 4. ملفات .tscn
  logger.info('[INFO] Generating .tscn scene files...');
  try {
    const scenes = await askGemini(`
${soul}
${library}

اكتب ملفات .tscn لـ Godot 4.6.2.
المشروع: "${idea.id}"
الملفات المتوفرة: main_scene.gd, player.gd, enemy.gd, weapon.gd, bullet.gd

القواعد الصارمة:
- load_steps = عدد ext_resource + عدد sub_resource بالضبط
- current = true في Camera3D
- contact_monitor = true + max_contacts_reported = 1 في bullet.tscn
- connection signal=body_entered في bullet.tscn
- collision_mask = 3 للعدو
- gravity_scale = 0.0 في bullet.tscn
- process_mode = 3 في main_scene.tscn
- جميع أسماء الملفات lowercase

أنتج JSON فقط:
{
  "main_scene.tscn": "...",
  "player.tscn":     "...",
  "enemy.tscn":      "...",
  "weapon.tscn":     "...",
  "bullet.tscn":     "..."
}`, 0.5, { maxOutputTokens: 8192 }, 'code-agent');

    for (const [filename, content] of Object.entries(scenes)) {
      if (typeof content !== 'string' || !content.trim()) {
        logger.warn(`[WARN] Empty scene: ${filename}`);
        continue;
      }
      writeProjectFile(slug, filename, fixLoadSteps(content));
      files.push(filename);
    }
  } catch (err) {
    logger.error('[ERROR] Scene generation failed', { error: err.message });
  }

  // 5. إصلاح Camera3D في player.tscn
  try {
    const playerTscnPath = join(__dirname, '..', 'godot-projects', slug, 'player.tscn');
    if (existsSync(playerTscnPath)) {
      let content = readFileSync(playerTscnPath, 'utf8');
      if (content.includes('type="Camera3D"') && !content.includes('current = true')) {
        content = content.replace(
          /(\[node name="[^"]*" type="Camera3D"[^\]]*\])/g,
          '$1\ncurrent = true'
        );
        writeFileSync(playerTscnPath, content, 'utf8');
        logger.info('[OK] Fixed Camera3D current=true in player.tscn');
      }
    }
  } catch (err) {
    logger.warn('[WARN] Could not fix Camera3D', { error: err.message });
  }

  // 6. worlds.json
  if (levels) {
    writeProjectFile(slug, 'worlds.json', JSON.stringify(levels, null, 2));
    files.push('worlds.json');
  }

  // 7. إضافة للمنتجات
  addToProducts(idea, art, levels);

  logger.info('[OK] Code Agent finished', { slug, totalFiles: files.length });
  return { slug, files, engine: 'godot', totalFiles: files.length };
}
