/**
 * code-agent.js — v2.0
 *
 * التغييرات عن v1.0:
 *  - maxOutputTokens: .gd=8192 / .tscn=16384
 *  - temperature: 0.7 → 0.2 لكل الكود
 *  - .tscn: كل ملف في استدعاء منفصل (بدل 5 في استدعاء واحد)
 *  - weapon.gd + bullet.gd في استدعاء واحد (توفير طلب)
 *  - كل .tscn يستلم الكود المقابل كمرجع
 *  - soul خارج prompt الرئيسي
 *
 * القواعد المطبقة:
 *  rule-056 : soulContext قبل كل عمل
 *  rule-058 : preset = 'Web' دائماً
 *  rule-070 : platform = 'Web' في Godot 4.x
 *  rule-087 : askGemini(prompt, temp, options, caller)
 *  rule-089 : كل الردود JSON
 *  rule-098 : askGemini فقط
 *  rule-099 : [INFO]/[OK]/[ERROR]/[WARN]
 *  rule-101 : maxOutputTokens لا maxTokens
 *  rule-102 : لا JSON.parse
 *  rule-110 : project.godot يُبنى محلياً
 *  rule-128 : caller logging
 *
 *  rule-146 : .gd  → maxOutputTokens: 8,192  / temperature: 0.2
 *  rule-147 : .tscn → maxOutputTokens: 16,384 / temperature: 0.2
 *  rule-148 : كل .tscn في استدعاء منفصل مع كوده كمرجع
 *  rule-149 : weapon.gd + bullet.gd في استدعاء واحد
 */

import { writeFileSync, mkdirSync, existsSync, readFileSync, readdirSync } from 'fs';
import { join, dirname }  from 'path';
import { fileURLToPath }  from 'url';
import { askGemini, canAfford } from './_gemini.js';
import { soulContext }    from './_soul.js';
import { readForAgent }   from './library-builder-agent.js';
import { logger }         from '../logger.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

// ══════════════════════════════════════════════════════════
// أدوات مساعدة
// ══════════════════════════════════════════════════════════

function writeProjectFile(slug, filename, content) {
  const dir = join(__dirname, '..', 'godot-projects', slug);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, filename), content, 'utf8');
  logger.info(`[OK] Written: ${slug}/${filename}`);
}

function generateExportPresets() {
  return `[preset.0]
name="Web"
platform="Web"
runnable=true
dedicated_server=false
custom_features=""
export_filter="all_resources"
include_filter=""
exclude_filter=""
export_path="./index.html"
patches=PackedStringArray()
encryption_include_filters=""
encryption_exclude_filters=""
encrypt_pck=false
encrypt_directory=false

[preset.0.options]
custom_template/debug=""
custom_template/release=""
variant/extensions_support=false
variant/thread_support=false
vram_texture_compression/for_desktop=true
vram_texture_compression/for_mobile=false
html/export_icon=true
html/custom_html_shell=""
html/head_include=""
html/canvas_resize_policy=2
html/focus_canvas_on_start=true
html/experimental_virtual_keyboard=false
progressive_web_app/enabled=false
progressive_web_app/offline_page=""
progressive_web_app/display=1
progressive_web_app/orientation=0
progressive_web_app/icon_144x144=""
progressive_web_app/icon_180x180=""
progressive_web_app/icon_512x512=""
progressive_web_app/background_color=Color(0, 0, 0, 1)
`;
}

function buildProjectGodot(idea) {
  return `; Engine configuration file.
; Generated by universe agents — Godot 4.6.2
config_version=5

[application]
config/name="${idea.name?.en || idea.id}"
run/main_scene="res://main_scene.tscn"
config/features=PackedStringArray("4.6", "Forward Plus")
config/icon="res://icon.svg"

[display]
window/size/viewport_width=1280
window/size/viewport_height=720

[input]
move_forward={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":87,"physical_keycode":87,"key_label":87,"unicode":119,"echo":false)]
}
move_back={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":83,"physical_keycode":83,"key_label":83,"unicode":115,"echo":false)]
}
move_left={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":65,"physical_keycode":65,"key_label":65,"unicode":97,"echo":false)]
}
move_right={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":68,"physical_keycode":68,"key_label":68,"unicode":100,"echo":false)]
}
jump={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":32,"physical_keycode":32,"key_label":32,"unicode":32,"echo":false)]
}
fire={
"deadzone": 0.5,
"events": [Object(InputEventMouseButton,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"button_mask":1,"position":Vector2(0, 0),"global_position":Vector2(0, 0),"factor":1.0,"button_index":1,"canceled":false,"pressed":true,"double_click":false)]
}
ui_cancel={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":4194305,"physical_keycode":4194305,"key_label":4194305,"unicode":0,"echo":false)]
}

[rendering]
renderer/rendering_method="forward_plus"
`;
}

function applyScriptRules(filename, code) {
  if (typeof code !== 'string') return code;
  code = code.replace(/^    /gm, '\t').replace(/^  /gm, '\t');
  if (code.includes('await') && code.includes('queue_free()') && !code.includes('is_inside_tree')) {
    code = code.replace(/(\tqueue_free\(\))/g, '\tif is_inside_tree():\n\t\tqueue_free()');
  }
  if (filename === 'player.gd' && !code.includes('add_to_group("player")')) {
    code = code.replace('func _ready():\n', 'func _ready():\n\tadd_to_group("player")\n');
  }
  if (filename === 'enemy.gd' && !code.includes('add_to_group("enemy")')) {
    code = code.replace('func _ready():\n', 'func _ready():\n\tadd_to_group("enemy")\n');
  }
  return code;
}

function fixLoadSteps(content) {
  if (typeof content !== 'string') return content;
  const ext = (content.match(/^\[ext_resource /gm) || []).length;
  const sub = (content.match(/^\[sub_resource /gm) || []).length;
  return content.replace(/\[gd_scene load_steps=\d+/, `[gd_scene load_steps=${ext + sub + 1}`);
}

function loadRecipes(domain) {
  const recipesDir = join(__dirname, '..', 'godot-recipes', domain);
  if (!existsSync(recipesDir)) return '';
  try {
    const files = readdirSync(recipesDir).filter(f => f.endsWith('.meta.json'));
    if (!files.length) return '';
    return files.slice(0, 3).map(f => {
      const meta = JSON.parse(readFileSync(join(recipesDir, f), 'utf8'));
      return `- ${meta.label}: ${meta.usage}`;
    }).join('\n');
  } catch { return ''; }
}

function addToProducts(idea, art, worlds) {
  const path     = join(__dirname, '..', 'products.json');
  const pub      = join(__dirname, '..', 'public', 'products.json');
  const products = existsSync(path) ? JSON.parse(readFileSync(path, 'utf8')) : [];
  if (products.find(p => p.id === idea.id)) {
    logger.info('[INFO] Product already exists', { id: idea.id });
    return;
  }
  products.unshift({
    id:           idea.id,
    slug:         idea.id,
    type:         'godot',
    category:     'game',
    status:       'available',
    templateFile: 'godot-wrapper.html',
    godotSlug:    idea.id,
    accent:       art?.accent    || '#00ff88',
    accentRgb:    art?.accentRgb || '0,255,136',
    gradient:     art?.gradient  || '135deg,#020209,#080820',
    name:         idea.name,
    desc:         idea.desc,
    tags:         idea.tags || [],
    iap:          [],
    levels:       worlds?.worlds?.map(w => ({
      id:         w.id,
      name:       w.name,
      difficulty: w.difficulty,
    })) || [],
    controls: {
      ar: { move: 'WASD للتحرك', look: 'الفأرة للنظر', fire: 'كليك يسار', jump: 'مسافة' },
      en: { move: 'WASD to move', look: 'Mouse to look', fire: 'Left click', jump: 'Space' },
    },
    generated:   true,
    generatedAt: new Date().toISOString(),
  });
  const json = JSON.stringify(products, null, 2);
  writeFileSync(path, json, 'utf8');
  // rule-109: انسخ إلى public/
  mkdirSync(join(__dirname, '..', 'public'), { recursive: true });
  writeFileSync(pub, json, 'utf8');
  logger.info('[OK] Product added + copied to public/', { id: idea.id });
}

// ══════════════════════════════════════════════════════════
// توليد GDScript
// ══════════════════════════════════════════════════════════

async function generateGDScripts(idea, story, levels, soul, library) {
  logger.info('[CODE] Generating GDScript files...');

  const heroName    = story?.mainCharacter?.name || 'Hero';
  const worldNames  = levels?.worlds?.slice(0, 3).map(w => w.name?.en).join(', ') || '';
  const movementTip = loadRecipes('movement');
  const files       = {};

  // ── 1. main_scene.gd ──────────────────────────────────
  try {
    const r = await askGemini(`${soul}
${library}

Godot 4.6.2 GDScript for main_scene.gd.
Game: "${idea.name?.en}".
Root node: Node3D.
Rules:
- process_mode = ALWAYS
- handle InputEventMouseButton + InputEventScreenTouch to start game
- pause / unpause logic with get_tree().paused
- export var for main menu CanvasLayer

Return JSON only — no text outside JSON:
{ "main_scene.gd": "<complete GDScript code>" }`,
      0.2, { maxOutputTokens: 8192, topP: 0.85 }, 'code-agent');

    files['main_scene.gd'] = r?.['main_scene.gd'];
  } catch (err) {
    logger.error('[ERROR] main_scene.gd failed', { error: err.message });
  }

  // ── 2. player.gd ──────────────────────────────────────
  try {
    const r = await askGemini(`${soul}
${library}

Godot 4.6.2 GDScript for player.gd.
Game: "${idea.name?.en}". Hero: ${heroName}.
${movementTip ? `Movement recipe:\n${movementTip}` : ''}
Rules:
- extends CharacterBody3D
- add_to_group("player") in _ready()
- WASD movement + mouse look (captured)
- jump with "jump" action
- fire with "fire" action — calls weapon.shoot()
- health system with signal player_died
- is_inside_tree() before any queue_free() after await

Return JSON only — no text outside JSON:
{ "player.gd": "<complete GDScript code>" }`,
      0.2, { maxOutputTokens: 8192, topP: 0.85 }, 'code-agent');

    files['player.gd'] = r?.['player.gd'];
  } catch (err) {
    logger.error('[ERROR] player.gd failed', { error: err.message });
  }

  // ── 3. enemy.gd ───────────────────────────────────────
  try {
    const r = await askGemini(`${soul}
${library}

Godot 4.6.2 GDScript for enemy.gd.
Game: "${idea.name?.en}". Worlds: ${worldNames}.
Rules:
- extends CharacterBody3D
- add_to_group("enemy") in _ready()
- NavigationAgent3D for pathfinding to player
- attack when distance < attack_range
- health + die() with is_inside_tree() check
- collision_layer = 2, collision_mask = 3

Return JSON only — no text outside JSON:
{ "enemy.gd": "<complete GDScript code>" }`,
      0.2, { maxOutputTokens: 8192, topP: 0.85 }, 'code-agent');

    files['enemy.gd'] = r?.['enemy.gd'];
  } catch (err) {
    logger.error('[ERROR] enemy.gd failed', { error: err.message });
  }

  // ── 4. weapon.gd + bullet.gd في استدعاء واحد ─────────
  try {
    const r = await askGemini(`${soul}
${library}

Godot 4.6.2 GDScript — two files in one call.

FILE 1: weapon.gd
- extends Node3D
- preload bullet scene: const BULLET = preload("res://bullet.tscn")
- Marker3D child named "muzzle_point"
- fire rate cooldown with can_shoot bool + Timer
- func shoot() — instantiates bullet at muzzle_point

FILE 2: bullet.gd
- extends RigidBody3D
- gravity_scale = 0.0
- linear_velocity set in _ready() from forward direction
- _on_body_entered(body): deal damage if body in "enemy" group
- is_inside_tree() before queue_free() after any await
- collision_layer = 4

Return JSON only — no text outside JSON:
{
  "weapon.gd": "<complete GDScript code>",
  "bullet.gd": "<complete GDScript code>"
}`,
      0.2, { maxOutputTokens: 8192, topP: 0.85 }, 'code-agent');

    files['weapon.gd'] = r?.['weapon.gd'];
    files['bullet.gd'] = r?.['bullet.gd'];
  } catch (err) {
    logger.error('[ERROR] weapon+bullet failed', { error: err.message });
  }

  return files;
}

// ══════════════════════════════════════════════════════════
// توليد .tscn — كل ملف منفصل مع كوده كمرجع
// ══════════════════════════════════════════════════════════

async function generateScenes(idea, gdFiles, soul) {
  logger.info('[CODE] Generating .tscn scene files...');

  const scenes = {};

  const SCENE_SPECS = [
    {
      name:     'main_scene.tscn',
      ref:      gdFiles['main_scene.gd'] || '',
      prompt:   `Godot 4.6.2 .tscn for main_scene.tscn.
Reference GDScript (main_scene.gd):
\`\`\`
${(gdFiles['main_scene.gd'] || '').slice(0, 2000)}
\`\`\`
Rules:
- Root: Node3D with script main_scene.gd
- process_mode = 3 (ALWAYS) on root
- WorldEnvironment child with default Environment
- DirectionalLight3D child
- CanvasLayer child for UI
- load_steps = exact count of ext_resource + sub_resource`,
    },
    {
      name:   'player.tscn',
      ref:    gdFiles['player.gd'] || '',
      prompt: `Godot 4.6.2 .tscn for player.tscn.
Reference GDScript (player.gd):
\`\`\`
${(gdFiles['player.gd'] || '').slice(0, 2000)}
\`\`\`
Rules:
- Root: CharacterBody3D with script player.gd
- CollisionShape3D child (CapsuleShape3D h=1.8 r=0.4)
- Node3D child "head" containing:
    Camera3D with current=true
    Node3D "weapon_holder" for weapon attachment
- load_steps = exact count`,
    },
    {
      name:   'enemy.tscn',
      ref:    gdFiles['enemy.gd'] || '',
      prompt: `Godot 4.6.2 .tscn for enemy.tscn.
Reference GDScript (enemy.gd):
\`\`\`
${(gdFiles['enemy.gd'] || '').slice(0, 2000)}
\`\`\`
Rules:
- Root: CharacterBody3D with script enemy.gd
- CollisionShape3D child (CapsuleShape3D h=1.8 r=0.4)
- NavigationAgent3D child
- collision_layer=2, collision_mask=3
- load_steps = exact count`,
    },
    {
      name:   'weapon.tscn',
      ref:    gdFiles['weapon.gd'] || '',
      prompt: `Godot 4.6.2 .tscn for weapon.tscn.
Reference GDScript (weapon.gd):
\`\`\`
${(gdFiles['weapon.gd'] || '').slice(0, 2000)}
\`\`\`
Rules:
- Root: Node3D with script weapon.gd
- Marker3D child named exactly "muzzle_point"
- Timer child named "FireTimer"
- MeshInstance3D child for visual
- load_steps = exact count`,
    },
    {
      name:   'bullet.tscn',
      ref:    gdFiles['bullet.gd'] || '',
      prompt: `Godot 4.6.2 .tscn for bullet.tscn.
Reference GDScript (bullet.gd):
\`\`\`
${(gdFiles['bullet.gd'] || '').slice(0, 2000)}
\`\`\`
Rules:
- Root: RigidBody3D with script bullet.gd
- CollisionShape3D child (SphereShape3D r=0.05)
- MeshInstance3D child (SphereMesh r=0.05)
- gravity_scale=0.0
- contact_monitor=true, max_contacts_reported=1
- collision_layer=4
- signal body_entered connected to _on_body_entered
- load_steps = exact count`,
    },
  ];

  for (const spec of SCENE_SPECS) {
    try {
      const r = await askGemini(`${soul}

${spec.prompt}

Return JSON only — no text outside JSON:
{ "${spec.name}": "<complete .tscn content>" }`,
        0.2,
        { maxOutputTokens: 16384, topP: 0.85 },
        'code-agent'
      );

      const content = r?.[spec.name];
      if (!content || typeof content !== 'string' || content.trim().length < 10) {
        logger.warn(`[WARN] Empty scene: ${spec.name}`);
        continue;
      }
      scenes[spec.name] = content;
      logger.info(`[OK] Scene generated: ${spec.name}`);
    } catch (err) {
      logger.error(`[ERROR] Scene failed: ${spec.name}`, { error: err.message });
    }
  }

  return scenes;
}

// ══════════════════════════════════════════════════════════
// إصلاح Camera3D
// ══════════════════════════════════════════════════════════

function fixCamera3D(slug) {
  try {
    const p = join(__dirname, '..', 'godot-projects', slug, 'player.tscn');
    if (!existsSync(p)) return;
    let c = readFileSync(p, 'utf8');
    if (c.includes('type="Camera3D"') && !c.includes('current = true')) {
      c = c.replace(
        /(\[node name="[^"]*" type="Camera3D"[^\]]*\])/g,
        '$1\ncurrent = true'
      );
      writeFileSync(p, c, 'utf8');
      logger.info('[OK] Fixed Camera3D current=true');
    }
  } catch (err) {
    logger.warn('[WARN] Could not fix Camera3D', { error: err.message });
  }
}

// ══════════════════════════════════════════════════════════
// الدالة الرئيسية
// ══════════════════════════════════════════════════════════

export async function run(idea, story, levels, art, template) {
  logger.info('[CODE] Code Agent v2.0 started', { id: idea.id, type: idea.type });

  const isGodot = idea.type === 'godot';
  if (!isGodot) {
    logger.info('[CODE] Non-Godot project — skipping');
    return { slug: idea.id, files: [], engine: 'phaser' };
  }

  // rule-153: تحقق من الحصة قبل البدء
  if (!canAfford('code-agent')) {
    throw new Error('InsufficientQuota: code-agent needs 9 calls');
  }

  const soul    = soulContext('code-agent');
  const library = readForAgent('code-agent', 8);
  const slug    = idea.id;
  const files   = [];

  // ── 1. ملفات ثابتة — بدون Gemini ──────────────────────
  writeProjectFile(slug, 'export_presets.cfg', generateExportPresets());
  files.push('export_presets.cfg');

  writeProjectFile(slug, 'project.godot', buildProjectGodot(idea));
  files.push('project.godot');

  // ── 2. GDScript — 4 استدعاءات ──────────────────────────
  const gdFiles = await generateGDScripts(idea, story, levels, soul, library);

  for (const [filename, code] of Object.entries(gdFiles)) {
    if (!code || typeof code !== 'string') {
      logger.warn(`[WARN] Missing code for ${filename}`);
      continue;
    }
    writeProjectFile(slug, filename, applyScriptRules(filename, code));
    files.push(filename);
  }

  // ── 3. .tscn — 5 استدعاءات منفصلة ─────────────────────
  const sceneFiles = await generateScenes(idea, gdFiles, soul);

  for (const [filename, content] of Object.entries(sceneFiles)) {
    writeProjectFile(slug, filename, fixLoadSteps(content));
    files.push(filename);
  }

  // ── 4. إصلاحات ما بعد التوليد ──────────────────────────
  fixCamera3D(slug);

  // ── 5. worlds.json ──────────────────────────────────────
  if (levels) {
    writeProjectFile(slug, 'worlds.json', JSON.stringify(levels, null, 2));
    files.push('worlds.json');
  }

  // ── 6. إضافة للمنتجات ───────────────────────────────────
  addToProducts(idea, art, levels);

  logger.info('[OK] Code Agent v2.0 finished', {
    slug,
    totalFiles:  files.length,
    gdScripts:   Object.keys(gdFiles).length,
    scenes:      Object.keys(sceneFiles).length,
    geminiCalls: 9,  // 4 gd + 5 tscn
  });

  return { slug, files, engine: 'godot', totalFiles: files.length };
}
