/**
 * idea-agent.js - الموديل المحدث Gemini 2.0 Flash
 */

import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const GEMINI_KEY = process.env.GEMINI_API_KEY;

async function gemini(prompt) {
  // استخدام الرابط المتوافق مع Gemini 2.0 Flash
  // تم استخدام v1beta لأن الموديلات الجديدة تتوفر فيها أولاً
  const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${GEMINI_KEY}`;
  
  const res = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      contents: [{ parts: [{ text: prompt }] }],
      generationConfig: { 
        temperature: 1.0, 
        maxOutputTokens: 2048,
        responseMimeType: "application/json" // إجبار الموديل على إرسال JSON فقط
      }
    })
  });

  const data = await res.json();
  
  if (data.error) {
    throw new Error(`Gemini API Error: ${data.error.message}`);
  }

  const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!text) throw new Error('Empty response from Gemini 2.0 Flash');
  
  return text;
}

export async function run() {
  const productsPath = join(__dirname, '..', 'products.json');
  const products = JSON.parse(readFileSync(productsPath, 'utf8'));
  const existingIds = products.slice(-20).map(p => p.id).join(', ');

  const TYPES = ['memory', 'puzzle', 'word', 'quiz', 'tool', 'arcade'];
  const type = TYPES[Math.floor(Math.random() * TYPES.length)];

  const prompt = `
Act as a world-class game designer. Suggest a unique "${type}" ${type === 'tool' ? 'app' : 'game'}.
Do not repeat: ${existingIds}

Return ONLY a valid JSON:
{
  "id": "slug-name",
  "type": "${type}",
  "category": "${type === 'tool' ? 'app' : 'game'}",
  "emoji": "🎮",
  "concept": "English description",
  "name": { "ar": "..", "en": "..", "fr": "..", "es": "..", "de": "..", "zh": ".." },
  "desc": { "ar": "..", "en": "..", "fr": "..", "es": "..", "de": "..", "zh": ".." },
  "tags": ["tag1", "tag2"]
}`;

  const raw = await gemini(prompt);
  
  try {
    // تنظيف الرد من أي زوائد
    const cleanJson = raw.replace(/```json|```/g, "").trim();
    const idea = JSON.parse(cleanJson);

    idea.generatedAt = new Date().toISOString();
    idea.generatedBy = 'gemini-2.0-flash';

    console.log(`✅ Idea Generated by 2.0 Flash: ${idea.id}`);
    return idea;
  } catch (err) {
    console.error('❌ Failed to parse JSON:', raw);
    throw new Error('Invalid JSON structure from Gemini');
  }
}
